collections:
  docs:
    output: true
defaults:
  -
    scope:
      path: "_docs"
    values:
      layout: doc
      type: doc
  -
    scope:
      path: "_docs/guides"
    values:
      layout: doc
      type: guides
  -
    scope:
      path: "_docs/style-business"
    values:
      layout: doc
      type: style-business
  -
    scope:
      path: "_docs/style-general"
    values:
      layout: doc
      type: style-general
  -
    scope:
      path: "_docs/style-sport"
    values:
      layout: doc
      type: style-sport
sass: 
  sass_dir: styleguide/_scss
  style: :compressed
sg_description: Fairfax Media Style Guide.
sg_favicon: /styleguide/branding/favicon.ico
sg_language: en
sg_styles: /styleguide/css/styleguide.css
sg_title: Style Guide